name: Lint and Format

on: [pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can push changes
          ref: ${{ github.head_ref }}  # Checkout the PR branch

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mccabe
          sudo apt-get install gcc

      # run black to format files
      - name: Install Black
        run: pip install black==23.11.0

      - name: Check files using the black formatter
        uses: k3tog/action-black@main
        id: action_black
        with:
          black_args: "."

      - name: If needed, commit black changes to the pull request
        if: steps.action_black.outputs.is_formatted == 'true'
        run: |
          black .
          git config --global user.name 'mijeongireneban'
          git config --global user.email 'mijeong.irene.ban@gmail.com'
          git add .
          git commit -m "Fixup: Format Python code with Black"
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # run flake8 linter
      - name: Run flake8
        uses: k3tog/flake8-action@main
        with:
          checkName: "Python Lint"
          path: .
          config: flake8.ini
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}